### ISSUE TITLE
Push emacs-grammarly(send-to-osx-grammarly) to Melpa?

### ISSUE THREAD

**Issue by jcs090218** [emacs-grammarly/send-to-osx-grammarly#1]
@mmagnus Not sure if you received my email about pushing your package [emacs-grammarly](https://github.com/mmagnus/emacs-grammarly) to Melpa?

I just created this organization [emacs-grammarly](https://github.com/emacs-grammarly) and  I would like to ask if you are willing to join and move your repository [emacs-grammarly](https://github.com/mmagnus/emacs-grammarly) to the organization? So I can help you with your package and take some responsibility from your package (basically help maintain, quick fix, response issue and review PR, etc). 

Of course, if you don't feel like it or having a trust issue. That's fine too! :)

Let me know what you think! Thank you!

---

BTW, You might notice I already made a PR for the first step of submission to Melpa. See https://github.com/mmagnus/emacs-grammarly/pull/11.

**Comment by jcs090218** [comment]
I have pushed it to my own elpa instead.

**Comment by mmagnus** [comment]
@jcs090218 great, thanks for your work!!!

**Comment by jcs090218** [comment]
@mmagnus Maybe you should still try to publish to MELPA though? Just my tiny opinion. :)

**Comment by mmagnus** [comment]
I don't really know how to do it, and right now I have no time to try to learn that ;) so it's fine for me, or we can just leave it here.

**Comment by jcs090218** [comment]
Let me know if you want to be part of this! Since you are the author of this package, I shall give you the access to this repo! :) (Only if you want to)
